apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  labels:
    app.kubernetes.io/name: APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: APP_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: APP_NAME
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: APP_NAME
        image: registry.cn-hongkong.aliyuncs.com/fotsg/user_center_api:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: jwt-keys
          mountPath: "/fot.sg/app/keys/"
          readOnly: true
        - name: app-secrets
          mountPath: "/fot.sg/app/_cfg/"
          readOnly: true
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/v1/APP_NAME/_healthcheck
            port: http
        readinessProbe:
          httpGet:
            path: /api/v1/APP_NAME/_healthcheck
            port: http
      volumes:
      - name: jwt-keys
        secret:
          secretName: jwt-keys
      - name: app-secrets
        secret:
          secretName: app-secrets
        