apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  labels:
    app.kubernetes.io/name: APP_NAME
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: APP_NAME
